### ISSUE TITLE
Shell ERROR

### ISSUE THREAD

**Issue by lean90** [l-ra/openeet#7] opened 2016-09-11 15:07 UTC
./send-req.sh signed-soap.xml
curl: (35) gnutls_handshake() failed: Error in the pull function.
~/Downloads/openeet-master/shell$

**Comment by l-ra** [comment] 2016-09-11 16:25
Please check if you have latest version. If you encountered the error after the 10th of September, you can have old version targeted to v2 API which was turned off on the 10th of September by GFR

**Comment by l-ra** [comment] 2016-09-11 18:36
Linux, Fedora 23, current version  (commit 680be49a) works for me. I'm closing the issue.

**Comment by lean90** [comment] 2016-09-12 01:57
I have latest version (Clone Master) but the error persists. 
I using command line at https://github.com/l-ra/openeet/tree/master/shell#sign-using-templates

You think what is different?

**Comment by l-ra** [comment] 2016-09-12 03:56
It seems there is a problem with curl on your system. What platform do you use? 
Try command `curl  https://pg.eet.cz/eet/services/EETServiceSOAP/v3` and uou should see something like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<env:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/"><env:Body><env:Fault><faultcode>env:Client</faultcode><faultstring>EET Request processing: Unrecognized resource requested in URI /eet/services/EETServiceSOAP/v3. Please, see EET service documentation.</faultstring></env:Fault></env:Body></env:Envelope>
```

If you get the error again, the problem is the curl / distribution / libraries.

I just added wget version of the send request script to the repo.  You can try the wget alternative using `./send-req-wget.sh work/signed-message`

**Closed as completed** 2016-09-12 03:56 UTC

**Comment by lean90** [comment] 2016-09-12 15:01
My sys : Ubuntu 16.04, PHP5.6, curl 7.47.0-1ubuntu2.1

`curl https://pg.eet.cz/eet/services/EETServiceSOAP/v3`

And get the error again!

I try wget command:

`wget -S -O - https://pg.eet.cz:443/eet/services/EETServiceSOAP/v3`
`--2016-09-12 08:10:29-- https://pg.eet.cz/eet/services/EETServiceSOAP/v3`
`Resolving pg.eet.cz (pg.eet.cz)... 5.145.105.129`
`Connecting to pg.eet.cz (pg.eet.cz)|5.145.105.129|:443... connected.`
`Unable to establish SSL connection.`

P/s: I try android application (https://github.com/l-ra/openeet/tree/master/android). but, get the same error

**Comment by l-ra** [comment] 2016-09-13 12:25
I have tested Ubuntu 16.04 in the docker container and everything works well . Android app works both on the phone and in the emulator. 
Could you please try command `openssl s_client -connect pg.eet.cz:443` and pase the output here ?

**Comment by lean90** [comment] 2016-09-14 00:50
Thanks you for support. 
EET service blocks my ip. 

Today, shell run is ok.
